spring:
  datasource:
    url: jdbc:mysql://docker-mysql:3306/piggy_bank_db
    username: root
    password: vikkidchamp
    driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
      hibernate:
        ddl-auto: update