spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    enabled: true
    path: /h2-console
    console:
      settings:
        web-allow-others: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG