spring:
#  datasource:
#    url: jdbc:mysql://docker-mysql:3306/piggy_bank_db
#    username: root
#    password: vikkidchamp
#    driverClassName: com.mysql.cj.jdbc.Driver
#    jpa:
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#          format_sql: true
#      hibernate:
#        ddl-auto: update
  security:
    oauth2:
      client:
        client-authentication-scheme: form
        scope: profile email
        registration:
          google:
            client-id: 770947724727-t64lg37nr4uoq2gfp8fe8fvun58e6r0p.apps.googleusercontent.com
            client-secret: ASuFOTrVu8MfB8P2f0yP68Mw

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/piggybankcert.p12
    key-store-password: piggybankcert
    key-store-type: PKCS12
    key-alias: piggybankcert


#To run Spring boot app with different application config profiles:
#mvn spring-boot:run -Dspring-boot.run.profiles=<profile name>